url: https://justgetwet.github.io
baseurl: /rainyblue
lang: ja
title: "Jekyll Pages"
description: "SSG JekyllのテーマとGithub Pages"
author: "Akira"

github: "https://github.com/justgetwet"
twitter: "/"
pinterest: "/"

# remote_theme: justgetwet/rainyblue